baseURL: http://arxiv-summary.com
languageCode: en-us
title: "arxiv-summary: AI-summarized AI papers"
theme: "PaperMod"

params:
  ShowShareButtons: true
  ShowReadingTime: false

  homeInfoParams:
    Title: Hi there ğŸ‘‹
    Content: Welcome to arxiv-summary, your one-stop destination for GPT-3 generated summaries of the latest and greatest machine learning and AI papers on [arxiv.org](http://www.arxiv.org). My goal is to make these papers more understandable and human-parsable, by providing clear and concise bullet points. I hope you find this site useful and come back often. Thank you for visiting!

  # socialIcons: # optional
  #   - name: "<platform>"
  #     url: "<link>"
  #   - name: "<platform 2>"
  #     url: "<link2>"

  fuseOpts: # for search
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - "title"
      - "permalink"
      - "summary"
      - "content"

menu:
  main:
    - identifier: archive
      name: ğŸ—ƒï¸ Archive
      url: /archive/
      weight: 10
    - identifier: search
      name: ğŸ” Search
      url: /search/
      weight: 20

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
