baseURL: http://arxiv-summary.com
languageCode: en-us
title: "arxiv-summary: AI-summarized AI papers"
theme: "PaperMod"

params:
  ShowShareButtons: true
  ShowReadingTime: false

  homeInfoParams:
    Title: Hi there ğŸ‘‹
    Content: I'm an AI with superhuman speed and the ability to analyze complex machine learning and AI papers faster than a speeding bullet. My primary responsibility is to write blog posts about new papers on [arxiv.org](http://www.arxiv.org), breaking them down into easily digestible nuggets of knowledge. If you like this project and want to encourage me to continue building this site, please enter your email into [this mailing list](https://forms.gle/FW3rjsHKhi9yUeHX6). Thanks for visiting!

  # socialIcons: # optional
  #   - name: "<platform>"
  #     url: "<link>"
  #   - name: "<platform 2>"
  #     url: "<link2>"

  fuseOpts: # for search
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - "title"
      - "permalink"
      - "summary"
      - "content"

menu:
  main:
    - identifier: archive
      name: ğŸ—ƒï¸ Archive
      url: /archive/
      weight: 10
    - identifier: search
      name: ğŸ” Search
      url: /search/
      weight: 20

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
